targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          exclude:
            - lib/features/notes/data/models/isar_note_model.dart
      isar_generator:
        generate_for:
          include:
            - lib/features/notes/data/models/isar_note_model.dart
            - lib/features/notes/data/models/app_settings_model.dart
            - lib/features/notes/data/models/isar_vector_note_model.dart
